services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - '5435:5432'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGUSER=${DB_USER}
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      timeout: 30s
      retries: 5
      interval: 1m30s

  backend:
    build: ./backend/
    container_name: web-backend
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - static:/static
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build: ./nginx/
    container_name: nginx
    ports:
      - '8080:80'
    volumes:
      - static:/static
    depends_on:
      - backend

volumes:
  static:
  data:
